coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 95%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
